In [17]:
import tensorflow as tf
import numpy as np

inputarr = np.array([[[1,1,1,1],              # Input shape: (2, 3, 4)
                   [2,2,2,2],
                   [3,3,3,3],
                   [4,4,4,4]],
                  [[5,5,5,5],
                   [6,6,6,6],
                   [7, 7, 7, 7],
                   [8,8,8,8]]])
diagonal = tf.zeros_like(inputarr[:,:,0] )
print( ' diagnoal: ', diagonal.numpy())
treated = tf.linalg.set_diag(inputarr, diagonal)

print( inputarr[:,0])
print( inputarr )
print( treated.numpy())

test = tf.constant([[1],[4]])
tiled = tf.tile( test, [2,20])
print( tiled.numpy())

 diagnoal:  [[0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [5 5 5 5]]
[[[1 1 1 1]
  [2 2 2 2]
  [3 3 3 3]
  [4 4 4 4]]

 [[5 5 5 5]
  [6 6 6 6]
  [7 7 7 7]
  [8 8 8 8]]]
[[[0 1 1 1]
  [2 0 2 2]
  [3 3 0 3]
  [4 4 4 0]]

 [[0 5 5 5]
  [6 0 6 6]
  [7 7 0 7]
  [8 8 8 0]]]
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]]


In [ ]:
list_num_incoming_ege =[]
condition = np.array( [[[ True,  True, False],
              [ False,  True,  True]],
             [[ True,  True, False],
              [ True,  False,  True]]])
batch_features = tf.reshape(condition,[-1,3])
temp = tf.compat.v1.where( condition )
temp1 = temp[:,0]
offset = 11 * temp1
expanded_offset = tf.expand_dims( offset, axis = 1)
tiling = tf.tile( expanded_offset, [1,2])
temp2 = temp[:,1:3]
true_indices_nodes = tiling + temp2
num_incoming = tf.reduce_sum(input_tensor=tf.cast(condition,dtype=tf.int32), axis=1)
num_incoming.shape
reshaped = tf.reshape( num_incoming, [1,6])
squeezed = tf.squeeze( reshaped )
not_masked = tf.ones_like(condition,dtype=tf.bool)
temp3 = tf.zeros_like(not_masked[0,:,0:2])
diag_zero = tf.linalg.set_diag(not_masked, temp3 )
list_num_incoming_ege.append( squeezed)
list_num_incoming_ege.append( squeezed)
final = tf.stack( list_num_incoming_ege)
print( temp )

In [ ]:
x = tf.expand_dims( tf.cast( tf.range(  6), tf.int64), axis=1 )
y = tf.random.uniform([4,1])
y = tf.tile( y,[1,3])
print(x)

In [ ]:
def dynamic_rnn(rnn_type='lstm'):
    # 创建输入数据,3代表batch size,6代表输入序列的最大步长(max time),4代表每个序列的维度
    X = np.random.randn(7, 6, 4)
 
    # 第二个输入的实际长度为4
    X[1, 4:] = 0
 
    #记录三个输入的实际步长
    X_lengths = [6, 4, 6]
 
    rnn_hidden_size = 5
    if rnn_type == 'lstm':
        cell = tf.compat.v1.nn.rnn_cell.BasicLSTMCell(num_units=rnn_hidden_size, state_is_tuple=True)
    else:
        cell = tf.compat.v1.nn.rnn_cell.GRUCell(num_units=rnn_hidden_size)
 
    outputs, last_states = tf.compat.v1.nn.dynamic_rnn(
        cell=cell,
        dtype=tf.float64,
        #sequence_length=X_lengths,
        inputs=X)
 
    with tf.compat.v1.Session() as session:
        session.run(tf.compat.v1.global_variables_initializer())
        o1, s1 = session.run([outputs, last_states])
        print(np.shape(o1))
        print(o1)
        print(np.shape(s1))
        print(s1)
 
if __name__ == '__main__':
    tf.compat.v1.disable_eager_execution()
    dynamic_rnn(rnn_type='lstm')