In [1]:
try:
    # %tensorflow_version only exists in Colab.
    %tensorflow_version 2.x
except Exception:
    pass

import tensorflow as tf
import numpy as np

In [2]:
# Create a 1D uint8 NumPy array comprising of first 25 natural numbers
input_tf = np.arange(0, 24)
nodes = 4
input_tf = tf.Variable( input_tf, dtype=tf.float32 )
input_tf = tf.reshape( input_tf, [-1, nodes, 3])
print( input_tf )
input_dist = input_tf[:,:,:2]
print( input_dist )

# Square the input tensor x
temp = tf.square(input_dist)
square_input = tf.reduce_sum(input_tensor = temp, axis=2)
print( temp )
print(square_input)
#x = tf.reshape( x, [2, 3, 2])
#x
# Reshape tensor x into a 5 x 5 matrix. 
row = tf.reshape( square_input, [-1,1, nodes])
col = tf.reshape( square_input, [-1, nodes, 1])
temp2 = tf.matmul(input_dist, input_dist, False, True )
temp3 = tf.maximum( row - 2 * temp2  + col, 0.0)
dist_matrix = tf.sqrt( temp3 )
#print( row )
#print( col )
#print( temp2 )
#print( temp3 )
print( dist_matrix )
not_masked = tf.ones_like( dist_matrix, )
not_masked

tf.Tensor(
[[[ 0.  1.  2.]
  [ 3.  4.  5.]
  [ 6.  7.  8.]
  [ 9. 10. 11.]]

 [[12. 13. 14.]
  [15. 16. 17.]
  [18. 19. 20.]
  [21. 22. 23.]]], shape=(2, 4, 3), dtype=float32)
tf.Tensor(
[[[ 0.  1.]
  [ 3.  4.]
  [ 6.  7.]
  [ 9. 10.]]

 [[12. 13.]
  [15. 16.]
  [18. 19.]
  [21. 22.]]], shape=(2, 4, 2), dtype=float32)
tf.Tensor(
[[[  0.   1.]
  [  9.  16.]
  [ 36.  49.]
  [ 81. 100.]]

 [[144. 169.]
  [225. 256.]
  [324. 361.]
  [441. 484.]]], shape=(2, 4, 2), dtype=float32)
tf.Tensor(
[[  1.  25.  85. 181.]
 [313. 481. 685. 925.]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[[ 0.         4.2426405  8.485281  12.7279215]
  [ 4.2426405  0.         4.2426405  8.485281 ]
  [ 8.485281   4.2426405  0.         4.2426405]
  [12.7279215  8.485281   4.2426405  0.       ]]

 [[ 0.         4.2426405  8.485281  12.7279215]
  [ 4.2426405  0.         4.2426405  8.485281 ]
  [ 8.485281   4.2426405  0.         4.2426405]
  [12.7279215  8.485281   4.2426405  0.       ]]], shape=(2, 4, 4), dtype=float32)


<tf.Tensor: shape=(2, 4, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [3]:
# Reshape tensor x into a 5 x 5 matrix. 
row = tf.reshape( square_input, [-1,1, nodes])
col = tf.reshape( square_input, [-1, nodes, 1])
temp2 = tf.matmul(input_dist, input_dist, False, True )
temp3 = tf.maximum( row - 2 * temp2  + col, 0.0)
dist_matrix = tf.sqrt( temp3 )
true_for_edge = tf.less_equal( dist_matrix, 5.0)
#print( true_for_edge )
#print( row )
#print( col )
#print( temp2 )
#print( temp3 )
#print( dist_matrix )
indices = tf.cast( tf.compat.v1.where( true_for_edge), dtype = tf.int32)
#print( indices)
offset = nodes * indices[:,0]
#print( indices )
#print( offset )
offset = tf.expand_dims( offset, axis = 1)
#print( offset )
#print( tf.tile(offset, [1,2]))
true_indices_nodes = offset + indices[:, 1:3]
#print( true_indices_nodes)
num_incoming = tf.reduce_sum( input_tensor = tf.cast( true_for_edge, dtype=tf.int32), axis = 1)
print( 'dist_matrix: ')
print( dist_matrix )
print( 'true for edge less than 5.0: ')
print( true_for_edge )
print( 'true for edge less than 5.0 type int32:')
print( tf.cast( true_for_edge, dtype=tf.int32) )
print( ' num incoming: ')
print( num_incoming)
print( ' num incoming reshaped:')
num_incoming = tf.reshape( num_incoming, [1,-1])
print( num_incoming )
print( ' num incoming squeezed: ')
num_incoming = tf.squeeze( num_incoming, 0)
print( num_incoming )
list_num_incoming_edge = []
list_num_incoming_edge.append( tf.cast( num_incoming, dtype=tf.float32))
print( 'list_num_incoming_edge: ', list_num_incoming_edge)
print( 'stacked: ', tf.stack( list_num_incoming_edge))

dist_matrix: 
tf.Tensor(
[[[ 0.         4.2426405  8.485281  12.7279215]
  [ 4.2426405  0.         4.2426405  8.485281 ]
  [ 8.485281   4.2426405  0.         4.2426405]
  [12.7279215  8.485281   4.2426405  0.       ]]

 [[ 0.         4.2426405  8.485281  12.7279215]
  [ 4.2426405  0.         4.2426405  8.485281 ]
  [ 8.485281   4.2426405  0.         4.2426405]
  [12.7279215  8.485281   4.2426405  0.       ]]], shape=(2, 4, 4), dtype=float32)
true for edge less than 5.0: 
tf.Tensor(
[[[ True  True False False]
  [ True  True  True False]
  [False  True  True  True]
  [False False  True  True]]

 [[ True  True False False]
  [ True  True  True False]
  [False  True  True  True]
  [False False  True  True]]], shape=(2, 4, 4), dtype=bool)
true for edge less than 5.0 type int32:
tf.Tensor(
[[[1 1 0 0]
  [1 1 1 0]
  [0 1 1 1]
  [0 0 1 1]]

 [[1 1 0 0]
  [1 1 1 0]
  [0 1 1 1]
  [0 0 1 1]]], shape=(2, 4, 4), dtype=int32)
 num incoming: 
tf.Tensor(
[[2 3 3 2]
 [2 3 3 2]], shape=(2, 4), dtype=in